### ISSUE TITLE
JCE workaround stopped worked from 1.8.0_101+

### ISSUE THREAD

**Issue by dpishchukhin** [cternes/openkeepass#46]
```
de.slackspace.openkeepass.exception.KeePassDatabaseUnreadable: The key has the wrong size. Have you installed Java Cryptography Extension (JCE)? Is the master key correct?
        at de.slackspace.openkeepass.crypto.Aes.transformKey(Aes.java:130)
        at de.slackspace.openkeepass.crypto.Decrypter.createAesKey(Decrypter.java:49)
        at de.slackspace.openkeepass.crypto.Decrypter.decryptDatabase(Decrypter.java:15)
        at de.slackspace.openkeepass.KeePassDatabase.decryptAndParseDatabase(KeePassDatabase.java:316)
        at de.slackspace.openkeepass.KeePassDatabase.openDatabase(KeePassDatabase.java:307)
        at de.slackspace.openkeepass.KeePassDatabase.openDatabase(KeePassDatabase.java:280)

```

**Comment by MGuitar24** [comment]
Also seeing this issue with JDK 8, JDK 7 seems to work.

**Comment by jmleep** [comment]
Same problem. Last supported version i found was the last version of 1.7.

**Comment by cternes** [comment]
We should accept that the workaround fails. I mean, the workaround itself was pretty hacky and it was basically a matter of time until it stopped working.

Currently I don't see any alternatives than installing JCE.

**Comment by MGuitar24** [comment]
I did install the JCE in the Java 8 JDK and it still did not work. Only switching to Java 7 seemed to solve this.

**Comment by cternes** [comment]
That's unusual, are you sure that you've installed the JCE correctly **AND** that you're actually using the right JDK where the JCE is installed? There should be no issue if the JCE is installed.

**Comment by dpishchukhin** [comment]
I found a solution, but it uses Unsafe. check here: [keepass-maven-plugin](https://github.com/knowhowlab/keepass-maven-plugin/blob/master/src/main/java/org/knowhowlab/maven/plugins/keepass/util/JceWorkaround.java)

**Comment by cternes** [comment]
Thanks @dpishchukhin. I will have a look at it in the next days.
