### ISSUE TITLE
Can't read other app's files

### ISSUE THREAD

**Issue by KostyaM** [cternes/openkeepass#62]
i create a file using KeepassDroid or KeePassFX. Then i added a group there. All works great. Decode successfully. Then I added an Entry in KeePassDroid and i have got an error when decoding:

de.slackspace.openkeepass.exception.KeePassDatabaseUnreadableException: Could not deserialize object to xml

I think, ok, maybe i can create database using this library. I did that. Encode, decode, all works great, but when I try to open this database in KeePassDroid i am getting an error:

Wrong event type 
(position: TEXT 49@27:17 in java.io.inputStream ...)

whats wrong with me or with this library

**Comment by cternes** [comment]
Probably nothing wrong with you :)
Can you provide an example of the broken database with anonymized passwords?

**Comment by KostyaM** [comment]
You mean database wich created in another app? Or database wich dont opens in another app?

**Comment by cternes** [comment]
The database which you have first created in KeepassDroid and openkeepass was not able to open with the `KeePassDatabaseUnreadableException`.

**Comment by KostyaM** [comment]
OK, here you go:
File created by keepassdroid. The password is "1". It contains 1 group and 1 entry. 
I am opening like this:

`val database = KeePassDatabase.getInstance(File(path)).openDatabase(password)`

Here is stacktrace 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.kocmuk.kdbxreader1/com.examp
![keepass](https://user-images.githubusercontent.com/33448856/40960875-aac6bf96-68a9-11e8-97c7-56546bc70f23.jpg)

```
le.kocmuk.kdbxreader1.MainActivity}: de.slackspace.openkeepass.exception.KeePassDatabaseUnreadableException: Could not deserialize object to xml
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6139)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: de.slackspace.openkeepass.exception.KeePassDatabaseUnreadableException: Could not deserialize object to xml
        at de.slackspace.openkeepass.parser.SimpleXmlParser.fromXml(SimpleXmlParser.java:28)
        at de.slackspace.openkeepass.parser.KeePassDatabaseXmlParser.fromXml(KeePassDatabaseXmlParser.java:17)
        at de.slackspace.openkeepass.api.KeePassDatabaseReader.parseDatabase(KeePassDatabaseReader.java:58)
        at de.slackspace.openkeepass.api.KeePassDatabaseReader.decryptAndParseDatabase(KeePassDatabaseReader.java:46)
        at de.slackspace.openkeepass.KeePassDatabase.openDatabase(KeePassDatabase.java:165)
        at com.example.kocmuk.kdbxreader1.KDBXOperator.read(KDBXOperator.kt:28)
        at com.example.kocmuk.kdbxreader1.MainActivity.onCreate(MainActivity.kt:30)
        at android.app.Activity.performCreate(Activity.java:6758)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6139) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(data=false, empty=true, entry=, inline=true, name=String, required=true, type=void) on field 'properties' private java.util.List de.slackspace.openkeepass.domain.Entry.properties for class de.slackspace.openkeepass.domain.Entry at line 1
        at org.simpleframework.xml.core.Composite.validate(Composite.java:644)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:449)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:144)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:619)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:144)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:619)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
        at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:144)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:619)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
        at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
        at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
        at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
        at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
        at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
        at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
        at org.simpleframework.xml.core.Composite.read(Composite.java:201)
        at org.simpleframework.xml.core.Composite.read(Composite.java:148)
        at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
        at org.simpleframework.xml.core.Persister.read(Persister.java:625)
        at org.simpleframework.xml.core.Persister.read(Persister.java:606)
        at org.simpleframework.xml.core.Persister.read(Persister.java:584)
        at org.simpleframework.xml.core.Persister.read(Persister.java:543)
        at org.simpleframework.xml.core.Persister.read(Persister.java:444)
        at de.slackspace.openkeepass.parser.SimpleXmlParser.fromXml(SimpleXmlParser.java:25)
        	... 18 more

```

P.S. Sorry for keepass file i renamed it format to jpg, because github don't allows to sand kdbx format. You can rename it to kdbx and then use
Sorry for kotlin language )))

**Comment by cternes** [comment]
Thanks, I will look into it.

**Comment by cternes** [comment]
I've found the issue that KeepassDroid does not set entry properties in the history entries. I think this is not correct. However, I've made my library more lenient in parsing and it should be able to open these files with the next version.

**Comment by cternes** [comment]
Yes, it’s released on maven central and on GitHub as well. 

I don’t know what other libraries do, but the file should be valid as it is openable with Keepass itself. You have to open an issue at the other library repositories if you want them to investigate.

**Comment by KostyaM** [comment]
Can you link me on it, because I see only your old repository. Yes, I am not too long on GitHub

**Comment by KostyaM** [comment]
I see only old version dependency, did it changed?

**Comment by KostyaM** [comment]
Thank you very much, all works great
