### ISSUE TITLE
openkeepass in Oracle 12c JVM  Wrong IV length: must be 16 bytes long

### ISSUE THREAD

**Issue by term73** [cternes/openkeepass#67]
Hi,

I am getting following exception:

Exception in thread "Root Thread" de.slackspace.openkeepass.exception.KeePassDatabaseUnreadableException: Could not decrypt keepass file. Master key wrong?
      at de.slackspace.openkeepass.crypto.Aes.createCryptoException(Aes.java:115)
      at de.slackspace.openkeepass.crypto.Aes.transformData(Aes.java:72)
      at de.slackspace.openkeepass.crypto.Aes.decrypt(Aes.java:41)
      at de.slackspace.openkeepass.crypto.Decrypter.processDatabaseEncryption(Decrypter.java:35)
      at de.slackspace.openkeepass.crypto.Decrypter.decryptDatabase(Decrypter.java:16)
      at de.slackspace.openkeepass.api.KeePassDatabaseReader.decryptStream(KeePassDatabaseReader.java:115)
      at de.slackspace.openkeepass.api.KeePassDatabaseReader.decryptAndParseDatabase(KeePassDatabaseReader.java:38)
      at de.slackspace.openkeepass.KeePassDatabase.openDatabase(KeePassDatabase.java:165)
      at KeepassClobUtil.getPwd(KEEPASSCLOBUTIL:299)
Caused by: java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long
      at com.sun.crypto.provider.CipherCore.init(CipherCore.java:525)
      at com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:346)
      at javax.crypto.Cipher.implInit(Cipher.java:806)
      at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
      at javax.crypto.Cipher.init(Cipher.java:1396)
      at javax.crypto.Cipher.init(Cipher.java:1327)
      at de.slackspace.openkeepass.crypto.Aes.transformData(Aes.java:63)
      ... 7 more 

JVM version inside of Oracle DB version 12.2 is 1.8.0_141. I have copied latest JCE files to following directories:

/oracle/product/12.2.0.1/db_1/javavm/lib/security 
/oracle/product/12.2.0.1/db_1/javavm/jdk/jdk8/lib/security 
/oracle/product/12.2.0.1/db_1/jdk/jre/lib/security 

I have also restarted the DB but still getting the error.
Everything works in local PC (jar built with JDK 1.8.0_141).

I have also tried to load policy files locally to server.

--load jars
declare
r varchar2(500);
begin
  R := SYS.DBMS_JAVA.SET_OUTPUT_TO_SQL('1','insert into joutput values (:1)','TEXT');
  SYS.DBMS_JAVA.LOADJAVA('-v -r -f /dataio/genio/projects/openkeepass/xpp3-1.1.3.3.jar');
  SYS.DBMS_JAVA.LOADJAVA('-v -r -f /dataio/genio/projects/openkeepass/core-1.54.0.0.jar');
  SYS.DBMS_JAVA.LOADJAVA('-v -r -f /dataio/genio/projects/openkeepass/simple-xml-2.7.1.jar');  
  SYS.DBMS_JAVA.LOADJAVA('-v -r -f /dataio/genio/projects/openkeepass/local_policy.jar');
  SYS.DBMS_JAVA.LOADJAVA('-v -r -f /dataio/genio/projects/openkeepass/US_export_policy.jar');

  
end;
/
 
Can you give a hint ?

**Comment by BenSikkens** [comment]
Oracle released Java 8 u162. In this version the unlimited policy is enabled by default. You no longer need to install the policy file in the JRE or set the security property crypto.policy.

https://bugs.openjdk.java.net/browse/JDK-8170157

**Comment by term73** [comment]
Hi,

The solution now works with Oracle 19c with OJVM 1.8.0_211.
and addition to the code:

       if (System.getProperty("java.security.egd") == null) {
          System.setProperty("java.security.egd", "file:///dev/urandom");
       }

best regards
